
System calls used:
open()	Opens a file and returns a file descriptor
read()	Reads data from a file into memory
write()	Writes data from memory to a file
close()	Closes an opened file descriptor


Control Transition Between User Space and Kernel Space
The C program initially executes in user space.
When the program calls open(), read(), write(), or close(), control transfers to kernel space through a system call.
The Linux kernel performs the requested file operation, such as opening, reading, writing, or closing a file.
After completing the operation, the kernel returns the result and control back to the user space program.


Analysis of strace cat sample.txt:

The strace utility monitors the interaction between a user program and the Linux kernel.
To demonstrate system call tracing, first create a file named sample.txt and add some text to it. Then execute the following command in the Linux terminal:
strace cat sample.txt
The strace utility displays the system calls generated by the cat command along with their arguments and return values.
When cat sample.txt is executed,

1.execve() system call is used to execute the cat program.
Kernel Service: Process creation and program execution

2.The openat() system call opens sample.txt with read-only permission.
Kernel Service: File-system access and file-descriptor allocation

3.The read() system call requests the kernel to read the contents of the file.
Kernel Service: Reads the contents of sample.txt into memory.

5.The write() system call sends the file contents to the terminal.
Kernel Service: Standard output and device I/O handling

6.The close() system call Closes the file after reading is completed.
Kernel Service: File-descriptor and resource release

7.The exit_group() system call Terminates the cat process.
Kernel Service: Process termination and cleanup

Thus, the strace command successfully traces the system calls generated by cat sample.txt, demonstrating how the command interacts with the Linux kernel for program execution, file access, data reading, output display, and process termination.
